version = 0.1

[default.deploy.parameters]
stack_name = "bff-aws-koa"
resolve_s3 = true
s3_prefix = "bff-aws-koa"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []

[default.global.parameters]
region = "us-west-2"
